services:
  zenvi.core:
    image: zenvi.core
    build:
      context: .
      dockerfile: Zenvi.Core/Dockerfile

  zenvi.client:
    image: zenvi.client
    build:
      context: .
      dockerfile: Zenvi.Client/Dockerfile